### ISSUE TITLE
[Feature]: Add wooden shear to `c:tools/shear` item tag

### ISSUE THREAD

**Issue by Phoupraw** [cech12/WoodenShears#17]
### Describe the Feature

`net.fabricmc.fabric.api.tag.convention.v2.ConventionalItemTags#SHEAR_TOOLS`

`c:tools/shear`

**Comment by cech12** [comment]
Hello @Phoupraw
Thanks for your suggestion? What is the benefit of that? :)

**Comment by Phoupraw** [comment]
Because this makes other mod recognize shears besides vanilla shears more easily, such as inventory tool or automation machine, (and my mod).

**Comment by cech12** [comment]
Thanks for your response :) I will add the shears to the tag when I have time :)

**Comment by cech12** [comment]
Added in the upcoming release 1.21-3.1.1.0.
Thanks again for your suggestion :)
