### ISSUE TITLE
[Bug]: Modded leaves don't drop anything

### ISSUE THREAD

**Issue by dopa2077** [cech12/WoodenShears#19]
### Minecraft Version

1.21

### Mod Loader

NeoForge

### Mod Loader Version

21.0.140

### Mod Version

3.2.0.1

### Modpack or other Mod

Mods used:

Just Enough Items
Wooden Shears
Biomes O' Plenty
Regions Unexplored

### Describe the Issue

Basically the wooden shear doesn't act like the normal vanilla shear. 
While using the wooden shear on modded leaves nothing it's dropped.

### Logs

Not needed.

### Do you use any performance-enhancing mods (e.g. OptiFine)?

No optimization mods we're used.

**Comment by cech12** [comment]
Thanks for your report! These twoo mods are not using the common tag "c:tools/shear" in their leaves loot tables. that should be used by all shears and loot tables that should be compatibile with other mods. I will open PRs for these mods when I have time :)

**Comment by cech12** [comment]
@dopa2077 I have opened PRs for the two mods:
- https://github.com/Glitchfiend/BiomesOPlenty/pull/2244
- https://github.com/UHQ-GAMES-MODS/RegionsUnexplored/pull/11

I leave with issue open until they are merged and released in a new mod version.

**Comment by cech12** [comment]
Biomes O Plenty has already merged and released the changes int the version 1.21-21.0.0.13

**Comment by cech12** [comment]
RegionsUnexplored had merged the changes for Fabric & NeoForge. I opened another PR for the Forge version of the mod: 
- https://github.com/UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE/pull/177

**Comment by cech12** [comment]
RegionsUnexplored 1.21 v0.5.6.1 released the changes for NeoForge and Fabric. The Forge PR is not merged yet, but this issue was related to NeoForge. Therefore this issue is fixed and closed.
@dopa2077 Thanks again for your report. If you find any other compatibility issues, feel free to open a new issue. :)

**Comment by UHQ-GAMES** [comment]
totally forgot to check forge PR's, my bad. Will include in the next patch
